### ISSUE TITLE
Quick Hamburger Suggestion

### ISSUE THREAD

**Issue by BillyParadise** [muhibbudins/beawesome#1]
Hi, looks great, except it seems right-aligning the hamburger is a standard practice these days.  I suggest modifying this line:

    <a href="javascript:void(0)" id="toggle" class="item"><h2><i class="sidebar icon"></i></h2></a>

to be a class of 'right item'.

**Comment by hibuno** [comment]
Sound good, you change sidebar align too?

**Comment by hibuno** [comment]
Thanks for your suggestion, i have completed this suggests. :)
